name: CI
on: [push, pull_request]
jobs:
  rage-lint:
    name: Lint RAGE Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: '3.10.7'
      - name: Lint Resources
        uses: GoatG33k/rage-lint-action@v1
        with:
          python-version: '3.10.7'
