name: CI
on: [push, pull_request]
jobs:
  rage-lint:
    name: Lint RAGE Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Resources
        uses: fkk-cz/rage-lint-action@v1.0.0
        
